import map from '../data/lastmod.json';

/**
 * The date a page's content last changed (YYYY-MM-DD), for the sitemap's
 * <lastmod> and structured data's dateModified. The map is generated by
 * scripts/lastmod.mjs; see the notes there.
 */
export function lastmodFor(path: string): string {
  const entry = (map as Record<string, { date: string }>)[path];
  if (!entry) throw new Error(`No lastmod for ${path}: run node scripts/lastmod.mjs`);
  return entry.date;
}
