// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

// Per-page dates, generated by scripts/lastmod.mjs (read from the committed map, not git history).
const lastmods = JSON.parse(readFileSync(new URL('./src/data/lastmod.json', import.meta.url), 'utf8'));

// The production origin. Change this if you deploy under a different domain.
export default defineConfig({
  site: 'https://stayput.dev',
  output: 'static',
  trailingSlash: 'never',
  build: { format: 'file' },
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/sw') && !page.includes('/llms') && !page.includes('/search-index'),
      serialize(item) {
        const path = new URL(item.url).pathname.replace(/(.)\/$/, '$1');
        const entry = lastmods[path];
        if (!entry) throw new Error(`No lastmod for ${path}: run node scripts/lastmod.mjs`);
        return { ...item, lastmod: entry.date };
      },
    }),
    // Copy the Wasm decoders into public/vendor/ before every build and dev server,
    // however astro is invoked (see scripts/vendor.mjs).
    { name: 'stayput-vendor', hooks: { 'astro:config:setup': async () => void (await import('./scripts/vendor.mjs')) } },
  ],
  vite: {
    build: { target: 'es2022', assetsInlineLimit: 0 },
    worker: { format: 'es' },
    resolve: {
      // onnxruntime-web's default wasm entry embeds its 14 MB .wasm as a build asset, which would
      // land in /_astro/ and be precached for every visitor. This entry loads it from /vendor/
      // instead (wasmPaths in src/lib/bg.worker.ts), only when the background remover runs.
      // transformers.js (speech to text) imports the WebGPU entry, which needs a 28 MB .wasm of its own;
      // it is pointed at the same WebAssembly-only build, already cached for the background remover.
      alias: [
        { find: /^onnxruntime-web\/wasm$/, replacement: fileURLToPath(new URL('./node_modules/onnxruntime-web/dist/ort.wasm.min.mjs', import.meta.url)) },
        { find: /^onnxruntime-web\/webgpu$/, replacement: fileURLToPath(new URL('./node_modules/onnxruntime-web/dist/ort.wasm.min.mjs', import.meta.url)) },
        // The vocal remover's fast path on WebGPU; it loads its own 27 MB .wasm from /vendor/, only there.
        { find: /^ort-webgpu$/, replacement: fileURLToPath(new URL('./node_modules/onnxruntime-web/dist/ort.webgpu.min.mjs', import.meta.url)) },
      ],
    },
  },
});
